# name: My Test Action

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main]
# jobs:
#   build:

#     runs-on: ubuntu-latest
  
#     steps:
#       - name: ActionCalvin
#         uses: calvincheng919/actionCalvin@v1.0.0-alpha

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: calvincheng919/actionCalvin@v1.0.1-alpha
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash