name: My Test Action

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main]
# jobs:
#   build:

#     runs-on: ubuntu-latest
  
#     steps:
#       - name: ActionCalvin
#         uses: calvincheng919/actionCalvin@v1.0.0-alpha

on: [push]

jobs:
  test_action_job:
    runs-on: ubuntu-latest
    name: Looker Marketplace JSON Tests
    steps:
      - uses: actions/checkout@v3
      - name: JS Automation Tests
        uses: calvincheng919/calvin-js-action-template@v2.2.3
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()                # run this step even if previous step failed
        with:
          name: JEST Tests                        # Name of the check run which will be created
          path: reports/jest-junit.xml            # Path to test results           path: reports/jest-*.xml    
          reporter: jest-junit                    # Format of test results