name: My Test Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main]
jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
      - name: ActionCalvin
        uses: calvincheng919/actionCalvin@v1.0.0-alpha