# name: My Test Action

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main]
# jobs:
#   build:

#     runs-on: ubuntu-latest
  
#     steps:
#       - name: ActionCalvin
#         uses: calvincheng919/actionCalvin@v1.0.0-alpha

on: [push]

jobs:
  test_action_job:
    runs-on: ubuntu-latest
    name: Test my action
    steps:
      - uses: actions/checkout@v3
      - name: Calvin JS Action Test
        uses: calvincheng919/calvin-js-action-template@v1.6
        with:
          milliseconds: 1000
          # working-directory: './'